[project]
name = "ttspy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-texttospeech>=2.25.1",
    "pyqt5>=5.15.11",
    "python-dotenv>=1.1.0",
]
